export const GET_MOTORCYCLES = 'GET_MOTORCYCLES';
export const GET_MOTORCYCLES_SUCCESS = 'GET_MOTORCYCLES_SUCCESS';
export const GET_MOTORCYCLES_ERROR = 'GET_MOTORCYCLES_ERROR';

export const SAVE_MOTORCYCLE = 'SAVE_MOTORCYCLE';
export const SAVE_MOTORCYCLE_SUCCESS = 'SAVE_MOTORCYCLE_SUCCESS';
export const SAVE_MOTORCYCLE_ERROR = 'SAVE_MOTORCYCLE_ERROR';